## First Attempt

In [1]:
from pathlib import Path
import numpy as np
from collections import defaultdict
import re

In [3]:
dtype = 'string'
txt=[]

f_in = Path('./Data Sets/day21data.txt')
with open(f_in,'r') as f:
    txt = f.read().split('\n')

if(dtype == 'int'):
    nums = []
    for num in txt:
        nums.append(int(num))
elif(dtype == 'float'):
    nums = []
    for num in txt:
        nums.append(float(num))
print(txt)
# print(nums)

['mxc ssdszsn phc llj nhnd fqqcnm njrcfg mrczqmj zfnttf tqkfx zvq rftbr jgbk kmlkx tzdks czvphx qpbl fzlrf zmsdzh qfslcb psqc rfx vnjxs lkgln sqhvzg qzjrtl hfzqf qhtvsr zdthsvl cgflg nggbtk mxq rdkrtr djdhrn nkzqj lcrs mhrlx hpbnj blvfz djhj ssrgt lpvfv fslqkg rzcps njdb jbtlfv cncpbssj lsgqf hbdv gbhjv drtdz flndv gpjr xqgb xvjk zjbgp rjc bfnnnrn gcptp prksl xdcp pdt xtgjslz fgptl kdm njqrhcc nqvnn lxldx spnd nlqhlsn tcclbr gpqgkt jfrlp hddd bmqzgvr rfxgl fgsr hjvzcp mxzb hqd (contains eggs, fish, peanuts)', 'zcphr pcslhrg strpjp hbbgk nqvnn rtq jqzklv fnlk mhrlx fgsr bvlb gpqgkt fqqcnm dhsssf pdhlzg dchvb njdb rms zppxp pdt nfgr th jbz tktj rtpff xvjk fqtc ldrgj jbtlfv hzmk tqkfx nppxr qzjrtl nlqhlsn qfslcb xbvrx jhv ssrgt xqgb nbgv kmlkx chgjqc nthsf vhjgg mcl fzlrf lzvh pmhhqrk hjzkg lpvfv jgbk xsk blvfz thtlt nfck lftqn mxq flndv lsgqf njqrhcc mrczqmj nnskqnmn rjc zfnttf sqhvzg rfxgl zmsdzh rxd zbxj phc rtmfg bfnnnrn kdm dfcgd (contains peanuts)', 'vhjpjdr nxrgp pdj njdb fgsr zmsd

In [4]:
test=[]

f_in = Path('./Data Sets/test2.txt')
with open(f_in,'r') as f:
    test = f.read().split('\n')

if(dtype == 'int'):
    testnums = []
    for num in test:
        testnums.append(int(num))
elif(dtype == 'float'):
    testnums = []
    for num in test:
        testnums.append(float(num))
print(test)
# print(testnums)

['mxmxvkd kfcds sqjhc nhms (contains dairy, fish)', 'trh fvjkl sbzzf mxmxvkd (contains dairy)', 'sqjhc fvjkl (contains soy)', 'sqjhc mxmxvkd sbzzf (contains fish)']


In [100]:
def parse_file(file):
    # create summary lists
    ingred_list = []
    allergen_list = []
    all_ingreds = set()
    all_allergens = set()
    allergen_dict = defaultdict(list)
    # loop through rows in file
    for row in file:
        
        # parse list from file
        ingreds, allergens = row[:-1].split(' (contains ')
        ingreds = ingreds.split()
        allergens = allergens.split(', ')
        
        # add to summary lists
        all_ingreds.update(ingreds)
        all_allergens.update(allergens)
        ingred_list.append(ingreds)
        allergen_list.append(allergens)
        
        # loop through allergens and add ingredients for food with allergen
        for alg in allergens:
            allergen_dict[alg].append(ingreds)
    return [ingred_list, allergen_list, all_ingreds, all_allergens, allergen_dict]

def count_good_ingreds(file):
    ingredients, allergens, all_ingredients, all_alergens, alg_dict = parse_file(file)
    
    allergic_foods = {}
    for alg in all_alergens:
        allergic_foods = find_food_with_allergen(alg, alg_dict, allergic_foods)
    allergic_foods = {
        'wheat': 'lzvh', 
        'nuts': 'pdt', 
        'soy': 'rjc', 
        'dairy': 'phc', 
        'eggs': 'spnd', 
        'fish': 'zmsdzh', 
        'sesame': 'lsgqf', 
        'peanuts': 'fqqcnm'
    }
    no_allergens = all_ingredients.copy()
#     bad_foods = allergic_foods.values()
    alg_foods = list(allergic_foods.values())
    print(alg_foods)
    no_allergens = no_allergens.difference(set(alg_foods))
    print('No Allergens:', no_allergens)
    print(allergic_foods)
    
    count = 0
    for ing in ingredients:
        for food in no_allergens:
            if(food in ing):
                count +=1
    output = list(allergic_foods.keys())
    sorted_output = sorted(output)
    answer = ""
    for word in sorted_output:
        answer += allergic_foods[word] + ','
    return answer
    
    return count
    return len(no_allergens)

def find_food_with_allergen(allergen, alg_dict, allergic_foods):
#     print(allergen)
    foods_to_check = alg_dict[allergen][0]
    
    print('Allergen', allergen)
    for food in foods_to_check:
        if(all(food in ingredient_list for ingredient_list in alg_dict[allergen])):
            allergic_foods[allergen] = food
            print(food)
    return allergic_foods

In [101]:
count_good_ingreds(txt)

Allergen wheat
fqqcnm
phc
lzvh
lsgqf
Allergen nuts
phc
pdt
Allergen soy
rjc
phc
Allergen dairy
phc
Allergen eggs
phc
zmsdzh
rjc
spnd
Allergen fish
phc
fqqcnm
zmsdzh
Allergen sesame
rjc
zmsdzh
phc
spnd
lsgqf
fqqcnm
Allergen peanuts
fqqcnm
pdt
['lzvh', 'pdt', 'rjc', 'phc', 'spnd', 'zmsdzh', 'lsgqf', 'fqqcnm']
No Allergens: {'qhtvsr', 'nkzqj', 'jgbk', 'smdlg', 'qdkk', 'hdtr', 'qjhq', 'qzjrtl', 'lkgln', 'ldrgj', 'zdthsvl', 'jlrt', 'vxmrk', 'mzrx', 'nlqhlsn', 'chgjqc', 'dxdrk', 'nfck', 'nhzthvn', 'rbjmdn', 'hzmk', 'pfrqf', 'njdb', 'mxq', 'kdm', 'kjjst', 'sfkcp', 'dxrsgs', 'cncpbssj', 'hddd', 'ksrjn', 'djdhrn', 'ssrgt', 'czmml', 'qlkfvk', 'rftbr', 'zbxj', 'cvbc', 'hqd', 'bxqpgx', 'rzcps', 'rlgr', 'czkxlg', 'hpbnj', 'xtgjslz', 'pmhhqrk', 'qfslcb', 'bggmsj', 'pcslhrg', 'mrczqmj', 'jfrlp', 'rms', 'rfx', 'fctmvrs', 'xgpdnz', 'sxsxm', 'rtq', 'vnjxs', 'jqgm', 'zjbgp', 'vnbfvkp', 'gbhjv', 'lcrs', 'bmqzgvr', 'jbz', 'cgflg', 'mcl', 'njrcfg', 'dgxnc', 'gvdstsc', 'nvmm', 'djhj', 'drtdz', 'vbkb', 'fzlrf

'phc,spnd,zmsdzh,pdt,fqqcnm,lsgqf,rjc,lzvh,'

In [27]:
print(parse_file(test))

[[['mxmxvkd', 'kfcds', 'sqjhc', 'nhm'], ['trh', 'fvjkl', 'sbzzf', 'mxmxvk'], ['sqjhc', 'fvjk'], ['sqjhc', 'mxmxvkd', 'sbzz']], [['dairy', 'fish'], ['dairy'], ['soy'], ['fish']], {'mxmxvkd', 'sbzz', 'trh', 'nhm', 'mxmxvk', 'fvjk', 'fvjkl', 'kfcds', 'sqjhc', 'sbzzf'}]


In [99]:
",".join(sorted(['lzvh', 'pdt', 'rjc', 'phc', 'spnd', 'zmsdzh', 'lsgqf', 'fqqcnm']))

'fqqcnm,lsgqf,lzvh,pdt,phc,rjc,spnd,zmsdzh'

In [31]:
class imagecell:
    def __init__(self, id_num, cell):
        self.idnum = id_num
        self.cell = cell
        self.sides
        self.a
        self.b
        self.c
        self.d

In [78]:
def get_edges(cell):
    edges = []
    
    # top and bottom
    edges.append(cell[0])
    edges.append(cell[-1])
    
    # sides
    left = []
    right = []
#     print(cell)
    for row in cell:
#         print(row)
        left.append(row[0])
        right.append(row[-1])
    edges.append(left)
    edges.append(right)
    
    return edges

def find_all_edges(idnums, cells):
    cell_to_edge = {}
    for idnum in idnums:
        cell_to_edge[idnum] = get_edges(cells[idnum])
    return cell_to_edge

def find_corners(file):
    ids, cells = parse_file(file)
    edge_map = find_all_edges(ids, cells)
#     print(ids)
#     print(cells)
    adjacent_cells = defaultdict(set)
    for idx in ids:
        checklist = ids.copy()
        checklist.remove(idx)
        for check in checklist:
            for edge in edge_map[idx]:
                if(edge in edge_map[check] or edge[::-1] in edge_map[check]):
                    adjacent_cells[check].add(idx)
                    adjacent_cells[idx].add(check)
    corner_product = 1
    for idx in ids:
        if len(adjacent_cells[idx]) == 2:
            corner_product *= idx
    print(corner_product)
    return adjacent_cells

In [80]:
adj_cells = find_corners(test)
adj_cells

20899048083289


defaultdict(set,
            {1951: {2311, 2729},
             2311: {1427, 1951, 3079},
             1427: {1489, 2311, 2473, 2729},
             3079: {2311, 2473},
             2729: {1427, 1951, 2971},
             1489: {1171, 1427, 2971},
             1171: {1489, 2473},
             2473: {1171, 1427, 3079},
             2971: {1489, 2729}})

In [111]:
def fill_image(adjacent_cells, corner_id):
    size = int(len(adjacent_cells)**(0.5))
    image = np.empty([size, size], dtype=int)
    image[0][0] = corner_id
    
    current = corner_id
    for idx in range(0 ,size):
        print('Index is', idx)
        current = image[0,idx]
        print(current)
        print(adjacent_cells[current])    
        for cell in adjacent_cells[current]:
            print(cell)
            print(adjacent_cells[cell])
            print(len(adjacent_cells[cell]))
            if(len(adjacent_cells[cell]) == 3):
                print('got here')
                image[0,idx+1] = cell
                break
    print(image)

In [112]:
fill_image(adj_cells, 1951)

Index is 0
1951
{2729, 2311}
2729
{1427, 2971, 1951}
3
got here
Index is 1
2729
{1427, 2971, 1951}
1427
{1489, 2729, 2473, 2311}
4
2971
{1489, 2729}
2
1951
{2729, 2311}
2
Index is 2
7471205
set()
[[   1951    2729 7471205]
 [2949229 7274595 7274604]
 [    114 5046356 3997776]]
