## First Attempt

In [231]:
from pathlib import Path
import numpy as np

In [232]:
dtype = 'string'
txt=[]

f_in = Path('./Data Sets/day14data.txt')
with open(f_in,'r') as f:
    txt = f.read().split('\n')

if(dtype == 'int'):
    nums = []
    for num in txt:
        nums.append(int(num))
elif(dtype == 'float'):
    nums = []
    for num in txt:
        nums.append(float(num))
print(txt)
# print(nums)

start = []
dxs = []
dys = []

xs = set()
ys = set()

coords = []
for line in txt:
    cs = line.split(' -> ')
    dxcs = []
    dycs = []
    for idx, c in enumerate(cs):
        x,y = c.split(',')
        x = int(x)
        y = int(y)
        print(x, y)
        xs.add(x)
        ys.add(y)
        
        if idx == 0:
            start.append((x,y))
            cx = x
            cy = y
        else:
            dx = x - cx
            dy = y - cy
            cx = x
            cy = y
            dxcs.append(dx)
            dycs.append(dy)
    dxs.append(dxcs)
    dys.append(dycs)

['502,19 -> 507,19', '523,100 -> 523,104 -> 519,104 -> 519,111 -> 528,111 -> 528,104 -> 526,104 -> 526,100', '488,59 -> 488,51 -> 488,59 -> 490,59 -> 490,52 -> 490,59 -> 492,59 -> 492,55 -> 492,59 -> 494,59 -> 494,52 -> 494,59 -> 496,59 -> 496,50 -> 496,59 -> 498,59 -> 498,58 -> 498,59 -> 500,59 -> 500,56 -> 500,59 -> 502,59 -> 502,56 -> 502,59 -> 504,59 -> 504,57 -> 504,59', '507,117 -> 521,117 -> 521,116', '517,34 -> 522,34', '513,97 -> 513,89 -> 513,97 -> 515,97 -> 515,94 -> 515,97 -> 517,97 -> 517,94 -> 517,97 -> 519,97 -> 519,93 -> 519,97 -> 521,97 -> 521,88 -> 521,97 -> 523,97 -> 523,94 -> 523,97', '513,97 -> 513,89 -> 513,97 -> 515,97 -> 515,94 -> 515,97 -> 517,97 -> 517,94 -> 517,97 -> 519,97 -> 519,93 -> 519,97 -> 521,97 -> 521,88 -> 521,97 -> 523,97 -> 523,94 -> 523,97', '510,75 -> 510,78 -> 505,78 -> 505,84 -> 518,84 -> 518,78 -> 515,78 -> 515,75', '503,34 -> 508,34', '501,15 -> 506,15', '523,136 -> 523,138 -> 518,138 -> 518,145 -> 535,145 -> 535,138 -> 528,138 -> 528,136', 

497 72
499 72
499 65
499 72
501 72
501 71
501 72
503 72
503 67
503 72
505 72
505 63
505 72
507 72
507 71
507 72
509 72
509 70
509 72
511 72
511 69
511 72
545 155
545 157
541 157
541 160
556 160
556 157
550 157
550 155
501 119
501 120
512 120
512 119
513 97
513 89
513 97
515 97
515 94
515 97
517 97
517 94
517 97
519 97
519 93
519 97
521 97
521 88
521 97
523 97
523 94
523 97
488 59
488 51
488 59
490 59
490 52
490 59
492 59
492 55
492 59
494 59
494 52
494 59
496 59
496 50
496 59
498 59
498 58
498 59
500 59
500 56
500 59
502 59
502 56
502 59
504 59
504 57
504 59
512 25
517 25
526 133
526 131
526 133
528 133
528 129
528 133
530 133
530 129
530 133
497 72
497 63
497 72
499 72
499 65
499 72
501 72
501 71
501 72
503 72
503 67
503 72
505 72
505 63
505 72
507 72
507 71
507 72
509 72
509 70
509 72
511 72
511 69
511 72
513 97
513 89
513 97
515 97
515 94
515 97
517 97
517 94
517 97
519 97
519 93
519 97
521 97
521 88
521 97
523 97
523 94
523 97
513 31
518 31
526 133
526 131
526 133
528 133
528 129
5

In [233]:
print(min(xs), max(xs))
print(min(ys), max(ys))

xrange = max(xs) - min(xs) + 3
yrange = (max(ys) - min(ys))*5
print(xrange, yrange)

482 556
13 160
77 735


In [234]:
grid = np.zeros((xrange,yrange))
grid.T

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [235]:
grid = np.zeros((xrange,yrange))

# loops through all the lines
for idx, c in enumerate(start):
    dx_list = dxs[idx]
    dy_list = dys[idx]
    
    cx, cy = c
    # loops through all segments in the lines
    for jdx, dx in enumerate(dx_list):
        dy = dy_list[jdx]
#         print(dx,dy)
        # loops through all the points to be set
        for delta in range(max(abs(dx),abs(dy))+1):
            if abs(dx) > 0:
                grid[cx + delta*np.sign(dx) - min(xs)+1, grid.shape[1] - max(ys) + (cy - 1)] = 1
#                 print(cx + delta - min(xs), cy - min(ys))
            else:
                grid[cx - min(xs)+1, grid.shape[1] - max(ys) + (cy + delta*np.sign(dy) - 1)] = 1
#                 print(cx - min(xs), cy + delta - min(ys))
        cx = cx + dx
        cy = cy + dy

In [236]:
grid.T

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [237]:
drop_point = 500 - min(xs) + 1

def fall_step(grid, xdx, ydx):
    if grid[xdx,ydx+1] == 0:
        return (xdx, ydx+1)
    elif grid[xdx-1,ydx+1] == 0:
        return (xdx-1, ydx+1)
    elif grid[xdx+1, ydx+1] == 0:
        return (xdx+1, ydx+1)
    else:
        return(xdx, ydx)
    
def sand_drop(grid, start):
    x, y = start
    
    still_falling = True
    while still_falling:
#         print(x,y)
        nx, ny = fall_step(grid, x, y)
        if nx == x and ny == y:
            still_falling = False
            grid[nx, ny] = 2
            return False
        elif ny == yrange-1:
            return True
        else:
            x = nx
            y = ny

def how_much_sand(grid, start):
    count = 0
    sand_stopped = False
    while not sand_stopped:
        sand_stopped = sand_drop(grid, start)
        count +=1
    return count-1
    
    
            

In [238]:
how_much_sand(grid, (drop_point, 0))

901

In [239]:
grid.T

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.]])

## Part 2

In [240]:
xrange = (max(xs))*2
yrange = (max(ys))+3
print(xrange, yrange)

grid = np.zeros((xrange,yrange),dtype=int)

# loops through all the lines
for idx, c in enumerate(start):
    dx_list = dxs[idx]
    dy_list = dys[idx]
    
    cx, cy = c
    # loops through all segments in the lines
    for jdx, dx in enumerate(dx_list):
        dy = dy_list[jdx]
        # loops through all the points to be set
        for delta in range(max(abs(dx),abs(dy))+1):
            if abs(dx) > 0:
                grid[cx + delta*np.sign(dx), cy] = 1
            else:
                grid[cx, cy + delta*np.sign(dy)] = 1
        cx = cx + dx
        cy = cy + dy
grid[:,grid.shape[1]-1] = 3

1112 163


In [241]:
grid[490:510,:].T

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [3, 3, 3, ..., 3, 3, 3]])

In [242]:
def fall_step(grid, xdx, ydx):
    if grid[xdx,ydx+1] == 0:
        return (xdx, ydx+1)
    elif grid[xdx-1,ydx+1] == 0:
        return (xdx-1, ydx+1)
    elif grid[xdx+1, ydx+1] == 0:
        return (xdx+1, ydx+1)
    else:
        return(xdx, ydx)
    
def sand_drop(grid, start):
    x, y = start
    
    still_falling = True
    while still_falling:
#         print(x,y)
        nx, ny = fall_step(grid, x, y)
        if ny == 0:
            return True
        elif nx == x and ny == y:
            still_falling = False
            grid[nx, ny] = 2
            return False
        else:
            x = nx
            y = ny

def how_much_sand(grid, start):
    count = 0
    sand_stopped = False
    while not sand_stopped:
        sand_stopped = sand_drop(grid, start)
        count +=1
    return count         

In [243]:
how_much_sand(grid, (500, 0))

24589

In [244]:
grid[490:510,:].T

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [3, 3, 3, ..., 3, 3, 3]])